# Generated by Django 3.2.16 on 2023-04-13 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20230412_1447'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='user_author_unique_relationships',
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='user_author_prevent_self_follow',
        ),
    ]
